version: '3.1'

services:
  mysql:
    image: mysql:8.0.32
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - 3306:3306

  api:
    image: node:16.19.1-slim
    restart: always
    container_name: api
    ports:
      - 3001:3001
    environment:
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - SERVER_PORT
    volumes:
      - ./:/usr/app
    user: node
    working_dir: /usr/app
    command: bash
    # As duas opções abaixo correspondem ao -it
    tty: true # -t
    stdin_open: true #-i 
    depends_on:
      - mysql
