api:
  image: node:16.19.1-slim
  restart: always
  container_name: api
  ports:
    - 3001:3001
  environment:
    DB_HOST: mysql
    DB_NAME: hospital_control
    DB_USER: root
    DB_PASSWORD: password
    PORT: 3001
  volumes:
    - ./:/usr/app
    - .env:/usr/app/.env
  user: node
  working_dir: /usr/app
  command: /bin/bash -c "until nc -z mysql 3306; do echo 'Waiting for MySQL...'; sleep 2; done; npm start"
  tty: true
  stdin_open: true
  depends_on:
    - mysql
